---
title: "CBA Changes Report"
subtitle: "2023 Season"
format:
  html:
      df-print: paged
      theme: cosmo
      self-contained: true
editor: visual
author: James Brown
echo: false
warning: false
message: false
---

```{r}
# Libraries and functions
library(tidyverse)
library(qreport)
library(kableExtra)

# Load data processing functions
source("../../Functions/data_processing_functions.R")
```

```{r}
#| results: asis

# Get Data
current_season_data <- get_fantasy_data(season = 2023)

# Get only players with at least one CBA
season_cbas <-
current_season_data |>
  select(Player = player_full_name,
         Round = round,
         Team = player_team,
         Opposition = opposition_team,
         CBAs = cbas,
         `CBA %` = cba_percentage) |> 
  mutate(Round = as.integer(str_remove(Round, "Round "))) |>
  mutate(`CBA %` = (100*`CBA %`) |> round(2)) |> 
  arrange(Player, Round) |> 
  filter(Round %in% c(max(Round), max(Round) - 1)) |> 
  mutate(`CBA Change` = `CBA %` - lag(`CBA %`), .by = Player) |> 
  mutate(`Previous Round CBA %` = lag(`CBA %`))

# Get biggest and smallest CBA Changes
cba_changes <-
season_cbas |> 
  select(Player, Team, `CBA %`, `Previous Round CBA %`, `CBA Change`) |> 
  filter(!is.na(`CBA Change`) & `CBA Change` != 0)

# List of Increases and Decreases
df_list <-
  list(
    "Increases" = cba_changes |> arrange(desc(`CBA Change`)) |> head(20),
    "Decreases" = cba_changes |> arrange(`CBA Change`) |> head(20)
)

# Output tables
maketabs(df_list, wide = FALSE)
```
