---
title: "Player Disposals Modelling"
execute:
  echo: false
  message: false
  warning: false
author: "James Brown"
date: "2023-03-23"
format:
  html:
    df-print: kable
    theme: cosmo
    self-contained: true
    toc: true
    toc-depth: 3
    fig-width: 8
    fig-height: 6
editor: visual
---

```{r}
# Libraries and functions
library(tidyverse)
library(qreport)

# Load data processing functions
source("../../Functions/data_processing_functions.R")

# Get current season data
current_season_data <-
  get_fantasy_data(season = lubridate::year(Sys.Date()))

# Historical
prev_season_data <- readr::read_rds("../../Data/afl_fantasy_2014_2022_data.rds")
  
# Combine to get total
player_history <- dplyr::bind_rows(current_season_data, prev_season_data)
```

## Disposal by team
First, look at which teams give up the most disposals to opposition players

```{r}
#| tbl-colwidths: true
#| column: screen
# Overall
current_season_data |> 
  group_by(opposition_team, round) |> 
  summarise(total_disposals = sum(disposals), median_disposals = median(disposals)) |> 
  pivot_wider(names_from = round, values_from = c("total_disposals", "median_disposals")) |> 
  janitor::clean_names() |> 
  relocate(median_disposals_round_1, .after = total_disposals_round_1) |> 
  mutate(total_disposals_overall = total_disposals_round_1 + total_disposals_round_2) |> 
  arrange(desc(total_disposals_overall))
```

```{r}
# Get player disposals dataset
player_disposals_data_all <-
player_history |> 
  select(player_full_name, opposition_team, season_name, round, match_result_string, venue, tog_percentage, disposals) |> 
  arrange(player_full_name, desc(season_name), desc(round)) |> 
  mutate(`proportion_15+_career` = mean(disposals >= 15), .by = player_full_name) |> 
    mutate(`proportion_20+_career` = mean(disposals >= 20), .by = player_full_name) |> 
  mutate(`proportion_25+_career` = mean(disposals >= 25), .by = player_full_name) |> 
    mutate(`proportion_30+_career` = mean(disposals >= 30), .by = player_full_name) |> 
      mutate(`proportion_35+_career` = mean(disposals >= 35), .by = player_full_name)

# Last season
player_disposals_data_2022 <-
player_history |> 
  select(player_full_name, opposition_team, season_name, round, match_result_string, venue, tog_percentage, disposals) |> 
  arrange(player_full_name, desc(season_name), desc(round)) |> 
  filter(season_name == '2022') |> 
  mutate(`proportion_15+_2022` = mean(disposals >= 15), .by = player_full_name) |> 
    mutate(`proportion_20+_2022` = mean(disposals >= 20), .by = player_full_name) |> 
  mutate(`proportion_25+_2022` = mean(disposals >= 25), .by = player_full_name) |> 
    mutate(`proportion_30+_2022` = mean(disposals >= 30), .by = player_full_name) |> 
      mutate(`proportion_35+_2022` = mean(disposals >= 35), .by = player_full_name) |> 
  distinct(player_full_name, .keep_all = TRUE) |> 
  select(player_full_name, contains("proportion"))

# This season
player_disposals_data_2023 <-
player_history |> 
  select(player_full_name, opposition_team, season_name, round, match_result_string, venue, tog_percentage, disposals) |> 
  arrange(player_full_name, desc(season_name), desc(round)) |> 
    filter(season_name == '2023') |> 
  mutate(`proportion_15+_2023` = mean(disposals >= 15), .by = player_full_name) |> 
    mutate(`proportion_20+_2023` = mean(disposals >= 20), .by = player_full_name) |> 
  mutate(`proportion_25+_2023` = mean(disposals >= 25), .by = player_full_name) |> 
    mutate(`proportion_30+_2023` = mean(disposals >= 30), .by = player_full_name) |> 
      mutate(`proportion_35+_2023` = mean(disposals >= 35), .by = player_full_name) |> 
  distinct(player_full_name, .keep_all = TRUE) |> 
  select(player_full_name, contains("proportion"))

# Join
player_disposals_data_all <-
player_disposals_data_all |> 
  left_join(player_disposals_data_2022) |> 
  left_join(player_disposals_data_2023) |> 
  select(player_full_name:disposals,
         contains("15+"),
         contains("20+"),
         contains("25+"),
         contains("30+"),
         contains("35+"))
  
```

```{r}
# Fit models
tom_mitchell_data <-
player_disposals_data_all |> 
  filter(season_name %in% c("2022", "2023")) |> 
  mutate(fifteen_plus_disposals = disposals >= 25)

```

