---
title: "Home vs Away"
subtitle: "2023 Season"
format:
  html:
      theme: cosmo
      df-print: paged
      self-contained: true
      toc: true
      fig-width: 8
      fig-height: 6
editor: visual
author: James Brown
echo: false
warning: false
message: false
---

```{r}
# Libraries and functions
library(tidyverse)
library(qreport)
library(kableExtra)
library(fitzRoy)

`%notin%` <- Negate(`%in%`)

# Load data processing functions
source("../../Functions/data_processing_functions.R")
```

```{r}
#| results: asis

# Get Data
current_season_data <- get_fantasy_data(season = 2022)

# Get player positions
positions <-
  fitzRoy::fetch_player_details_afl(season = 2023) |> 
  transmute(player_full_name = str_glue("{firstName} {surname}"),
            position = str_replace(position, "_", " ")) |> 
  mutate(position = str_to_title(position))

# Join with position data
current_season_data <-
current_season_data |> 
  left_join(positions)

# Add home or away
current_season_data <-
current_season_data |> 
  mutate(home = home_team == player_team)
```

```{r}
# Compare home and away performance by team
plot_player_home_vs_away <- function(player_name) {
  
  # Get player dataframe
  player_data <-
  current_season_data |> 
  filter(player_full_name == player_name)
  
  # Get player season average
  overall_avg <- mean(player_data$fantasy_points)
    
  # Produce plot
player_data |> 
  select(match_name, round, venue, fantasy_points, home) |> 
  ggplot(aes(x = round, y = fantasy_points, colour = home)) +
  geom_point(size = 3) +
  geom_hline(yintercept = overall_avg, linetype = "dashed", color = "black", size = 1) +
  scale_colour_manual(values = c("TRUE" = "green", "FALSE" = "red")) +
  labs(title = "Fantasy Points per Round",
       x = "Round",
       y = "Fantasy Points",
       colour = "Home Game") +
  theme(text = element_text(size = 14),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 18))
}

plot_player_home_vs_away("Isaac Smith")
```

```{r}
# Get outside midfielder data
outside_mid_data <-
current_season_data |>
  filter(position == "Midfielder") |> 
  filter(tog_percentage > 50) |> 
  filter(mean(hitouts) <= 2, .by = player_full_name) |> 
  filter(player_full_name %notin% inside_mid_data$player_full_name) |> 
  select(player_full_name, venue, opposition_team, fantasy_points, marks) |>
  arrange(player_full_name, opposition_team)

outside_mid_data |> 
  summarise(avg_points = mean(fantasy_points), .by = venue) |> 
  arrange(desc(avg_points))

# Get inside midfielder data
inside_mid_data <-
current_season_data |> 
  filter(tog_percentage > 50) |> 
  filter(mean(cba_percentage) >= 0.45, .by = player_full_name) |> 
  filter(mean(hitouts) <= 2, .by = player_full_name) |> 
  select(player_full_name, venue,opposition_team, fantasy_points,disposals) |>
  arrange(player_full_name, opposition_team)

inside_mid_data |> 
  summarise(avg_disposals = mean(disposals), .by = venue) |> 
  arrange(desc(avg_disposals))
```
